/* Generated By:JavaCC: Do not edit this line. SearchLogicConstants.java */
package com.fzy.core.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SearchLogicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PARAM = 5;
  /** RegularExpression Id. */
  int EQUALS = 6;
  /** RegularExpression Id. */
  int GREAT_THAN = 7;
  /** RegularExpression Id. */
  int LESS_THAN = 8;
  /** RegularExpression Id. */
  int GREAT_THAN_OR_EQUAL_TO = 9;
  /** RegularExpression Id. */
  int LESS_THAN_OR_EQUAL_TO = 10;
  /** RegularExpression Id. */
  int NULL = 11;
  /** RegularExpression Id. */
  int NOT_EQUAL = 12;
  /** RegularExpression Id. */
  int NOT_NULL = 13;
  /** RegularExpression Id. */
  int LIKE = 14;
  /** RegularExpression Id. */
  int START_WITH = 15;
  /** RegularExpression Id. */
  int END_WITH = 16;
  /** RegularExpression Id. */
  int NOT_START_WITH = 17;
  /** RegularExpression Id. */
  int NOT_END_WITH = 18;
  /** RegularExpression Id. */
  int NOT_LIKE = 19;
  /** RegularExpression Id. */
  int BLANK = 20;
  /** RegularExpression Id. */
  int ASC = 21;
  /** RegularExpression Id. */
  int DESC = 22;
  /** RegularExpression Id. */
  int DESC_NULL_FIRST = 23;
  /** RegularExpression Id. */
  int ASC_NULL_LAST = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 27;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<PARAM>",
    "\"_e\"",
    "\"_g\"",
    "\"_l\"",
    "\"_ge\"",
    "\"_le\"",
    "\"_nl\"",
    "\"_ne\"",
    "\"_nnl\"",
    "\"_lk\"",
    "\"_sw\"",
    "\"_ew\"",
    "\"_nsw\"",
    "\"_new\"",
    "\"_nlk\"",
    "\"_bk\"",
    "\"_ac\"",
    "\"_dc\"",
    "\"_dcf\"",
    "\"_acl\"",
    "\"_o\"",
    "\"_a\"",
    "\"_lp\"",
    "\"_rp\"",
  };

}
